### ISSUE TITLE
Explorer Licence: Is there any way to display wich files are involved in cyclic dependencies?

### ISSUE THREAD

**Issue by softdays** [sonargraph/sonar-sonargraph-integration#7]
I've installed sonargraph plugin and I finally got the following results:
![sonargraph](https://cloud.githubusercontent.com/assets/948293/20028810/e13b8df2-a33b-11e6-8a7c-b868fff5677b.png)

Is there any way to display wich files are involved in cyclic dependencies?

**Comment by ingmarkellner** [comment]
Hi,
no, with the SonarQube integration, you cannot see that.
That's by design, because for closer inspection of something complex like a cycle group, the standalone Sonargraph application offers better user interactions for code exploration.
The screenshot shows how the details behind a dependency are shown in the "Parser Dependencies (Out)" view.
![cycleinspectionsonargraph](https://cloud.githubusercontent.com/assets/3921099/20031683/a64cf646-a37b-11e6-9ab7-9bac0dde2de5.png)

There is additionally a more technical reason:
SonarQube is focussed on the physical package structure, whereas Sonargraph calculates package cycles based on "logical" namespaces. What the means, is described in our user manual (http://eclipse.hello2morrow.com/doc/standalone/content/logical_models.html): "[...] Sonargraph maps all physical namespaces that have the same name into a single logical namespace. This mapping can be system-based or module-based [...]".
As a result, we cannot reliably pin-point a physical package in SonarQube to attach an issue if it is referring to a logical namespace.

**Comment by softdays** [comment]
Many thanks for this very clear explanation. I will use the sonargraph integration widget as an alert and the standalone product to visualize cycle details.

**Comment by ingmarkellner** [comment]
As an additional side note: 
You can generated a HTML report with SonargraphBuild that contains info about the involved elements in a cycle:
![grafik](https://cloud.githubusercontent.com/assets/3921099/22378205/1b4831d4-e4b5-11e6-88bb-9fdb5f6ad24e.png)
